language: minimal

services:
  - docker

before_install:
  - docker version
  - docker-compose version

before_script:
  - docker-compose up --build -d
  - docker-compose ps

script:
  - export | grep -o "\w*=.*$" | tr -d \" > .env
  - docker-compose run web pytest