language: minimal

services:
  - docker

before_install:
  - docker version
  - docker-compose version

before_script:
  - docker-compose up --build -d
  - docker-compose ps
  - export > .env

script:
  - docker-compose run web python manage.py pytest