language: minimal

services:
  - docker

before_install:
  - docker version
  - docker-compose version

before_script:
  - docker-compose up --build -d
  - docker-compose ps

script:
  - export | grep -o "\w*=.*$" > .env
  - cat .env
  - ls
  - docker-compose run web python manage.py pytest