language: python

services:
  - docker

before_install:
  - docker version
  - docker-compose version

before_script:
  - docker-compose up --build -d
  - docker-compose ps

script:
  - docker-compose run web python manage.py tests