version: '3'

services:
  db:
    image: "postgres:11-alpine"
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8001"
    volumes:
      - .:/opt/app/
      - /dev/shm:/dev/shm
    environment:
      DISPLAY: :1.0
    ports:
      - "8001:8001"
    depends_on:
     - db

volumes:
  db_data:

